_TEXT SEGMENT BYTE PUBLIC 'CODE'
    ASSUME CS:_TEXT, DS:_TEXT
    PUBLIC mnem_unit
    EXTRN mff0:FAR
    EXTRN mfb3:FAR
    EXTRN mf196:FAR
    EXTRN mf4f:FAR
    EXTRN mf104:FAR
    EXTRN mf140:FAR
    EXTRN mf150:FAR
    EXTRN mf120:FAR
    EXTRN mf166:FAR
    EXTRN mf10:FAR
    EXTRN mf77:FAR
    EXTRN mf176:FAR
    EXTRN mf186:FAR
    EXTRN mf63:FAR
    EXTRN mf1a6:FAR
    EXTRN mf110:FAR
    EXTRN mf134:FAR
mnem_unit:
    push bp
    mov bp,sp
    sub sp,4h
    push di
    push si
    mov ax,14h
    mov dx,0F036h
    push dx
    push ax
    call mf10
    add sp,4h
    mov bx,1396h
    mov cx,3420h
    mov word ptr [bp-4h],bx
    mov word ptr [bp-2h],cx
    push ds
    push cx
    mov di,ax
    mov si,bx
    mov es,dx
    pop ds
    mov cx,0FFFFh
    xor ax,ax
    repne scasb
    not cx
    sub di,cx
    db 87h, 0FEh ; override
    push ds
    push dx
    pop ds
    pop es
    shr cx,1
    rep movsw
    adc cx,cx
    rep movsb
    pop ds
    mov ax,1h
    push ax
    mov ax,88h
    push ax
    call mf4f
    add sp,4h
    or ax,ax
    jnz short lbl6Ff
    mov ax,1h
    push ax
    mov ax,89h
    push ax
    call mf63
    add sp,4h
    or ax,ax
    jz short lblABf
lbl6Ff:
    mov ax,15h
    mov dx,0F036h
    push dx
    push ax
    call mf77
    add sp,4h
    mov di,ax
    mov es,dx
    push ds
    lds si, dword ptr [bp-4h]
    mov cx,0FFFFh
    xor ax,ax
    repne scasb
    not cx
    sub di,cx
    mov bx,cx
    db 87h, 0FEh ; override
    push ds
    push dx
    pop ds
    pop es
    mov cx,0FFFFh
    repne scasb
    dec di
    mov cx,bx
    shr cx,1
    rep movsw
    adc cx,cx
    rep movsb
    pop ds
lblABf:
    mov ax,16h
    mov dx,0F036h
    push dx
    push ax
    call mfb3
    add sp,4h
    mov di,ax
    mov es,dx
    push ds
    lds si, dword ptr [bp-4h]
    mov cx,0FFFFh
    xor ax,ax
    repne scasb
    not cx
    sub di,cx
    mov bx,cx
    db 87h, 0FEh ; override
    push ds
    push dx
    pop ds
    pop es
    mov cx,0FFFFh
    repne scasb
    dec di
    mov cx,bx
    shr cx,1
    rep movsw
    adc cx,cx
    rep movsb
    pop ds
    push ax
    mov cx,1h
    push cx
    mov dx,8Bh
    push dx
    call mff0
    add sp,6h
    mov ax,1h
    push ax
    mov cx,86h
    push cx
    mov cx,88h
    push cx
    call mf104
    add sp,6h
    mov ax,88h
    push ax
    call mf110
    add sp,2h
    mov ax,122h
    push ax
    mov cx,88h
    push cx
    call mf120
    add sp,4h
    mov ax,1h
    push ax
    mov ax,87h
    push ax
    mov ax,89h
    push ax
    call mf134
    add sp,6h
    mov ax,89h
    push ax
    call mf140
    add sp,2h
    mov ax,122h
    push ax
    mov ax,89h
    push ax
    call mf150
    add sp,4h
    xor ax,ax
    mov byte ptr ds:[343h],al
    push ax
    mov cx,80h
    push cx
    mov cx,8Ah
    push cx
    call mf166
    add sp,6h
    xor ax,ax
    push ax
    push ax
    mov ax,93h
    push ax
    call mf176
    add sp,6h
    mov ax,0Ah
    push ax
    mov ax,83h
    push ax
    call mf186
    add sp,4h
    mov ax,0Eh
    push ax
    mov ax,83h
    push ax
    call mf196
    add sp,4h
    mov ax,2Ch
    push ax
    mov ax,83h
    push ax
    call mf1a6
    add sp,4h
    mov ax,word ptr [bp-4h]
    mov dx,word ptr [bp-2h]
    pop si
    pop di
    mov sp,bp
    pop bp
    retf
_TEXT ENDS
    END
